// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: TSWPCommandArchives_sos.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct TSWP_CharacterStyleChangePropertyCommand_GArchive {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var `super`: TSWP_StorageActionCommandArchive {
    get {return _super ?? TSWP_StorageActionCommandArchive()}
    set {_super = newValue}
  }
  /// Returns true if ``super`` has been explicitly set.
  var hasSuper: Bool {return self._super != nil}
  /// Clears the value of ``super``. Subsequent reads from it will return its default value.
  mutating func clearSuper() {self._super = nil}

  var rangeList: [TSP_Range] = []

  var rangeListUndefined: Bool {
    get {return _rangeListUndefined ?? false}
    set {_rangeListUndefined = newValue}
  }
  /// Returns true if `rangeListUndefined` has been explicitly set.
  var hasRangeListUndefined: Bool {return self._rangeListUndefined != nil}
  /// Clears the value of `rangeListUndefined`. Subsequent reads from it will return its default value.
  mutating func clearRangeListUndefined() {self._rangeListUndefined = nil}

  var changeList: [TSWP_CharacterStylePropertyChangeSetArchive] = []

  var changeListUndefined: Bool {
    get {return _changeListUndefined ?? false}
    set {_changeListUndefined = newValue}
  }
  /// Returns true if `changeListUndefined` has been explicitly set.
  var hasChangeListUndefined: Bool {return self._changeListUndefined != nil}
  /// Clears the value of `changeListUndefined`. Subsequent reads from it will return its default value.
  mutating func clearChangeListUndefined() {self._changeListUndefined = nil}

  var disableCharacterStylePromotion: Bool {
    get {return _disableCharacterStylePromotion ?? false}
    set {_disableCharacterStylePromotion = newValue}
  }
  /// Returns true if `disableCharacterStylePromotion` has been explicitly set.
  var hasDisableCharacterStylePromotion: Bool {return self._disableCharacterStylePromotion != nil}
  /// Clears the value of `disableCharacterStylePromotion`. Subsequent reads from it will return its default value.
  mutating func clearDisableCharacterStylePromotion() {self._disableCharacterStylePromotion = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _super: TSWP_StorageActionCommandArchive? = nil
  fileprivate var _rangeListUndefined: Bool? = nil
  fileprivate var _changeListUndefined: Bool? = nil
  fileprivate var _disableCharacterStylePromotion: Bool? = nil
}

struct TSWP_ParagraphStyleChangePropertyCommand_GArchive {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var `super`: TSWP_StorageActionCommandArchive {
    get {return _super ?? TSWP_StorageActionCommandArchive()}
    set {_super = newValue}
  }
  /// Returns true if ``super`` has been explicitly set.
  var hasSuper: Bool {return self._super != nil}
  /// Clears the value of ``super``. Subsequent reads from it will return its default value.
  mutating func clearSuper() {self._super = nil}

  var rangeList: [TSP_Range] = []

  var rangeListUndefined: Bool {
    get {return _rangeListUndefined ?? false}
    set {_rangeListUndefined = newValue}
  }
  /// Returns true if `rangeListUndefined` has been explicitly set.
  var hasRangeListUndefined: Bool {return self._rangeListUndefined != nil}
  /// Clears the value of `rangeListUndefined`. Subsequent reads from it will return its default value.
  mutating func clearRangeListUndefined() {self._rangeListUndefined = nil}

  var changeList: [TSWP_ParagraphStylePropertyChangeSetArchive] = []

  var changeListUndefined: Bool {
    get {return _changeListUndefined ?? false}
    set {_changeListUndefined = newValue}
  }
  /// Returns true if `changeListUndefined` has been explicitly set.
  var hasChangeListUndefined: Bool {return self._changeListUndefined != nil}
  /// Clears the value of `changeListUndefined`. Subsequent reads from it will return its default value.
  mutating func clearChangeListUndefined() {self._changeListUndefined = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _super: TSWP_StorageActionCommandArchive? = nil
  fileprivate var _rangeListUndefined: Bool? = nil
  fileprivate var _changeListUndefined: Bool? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "TSWP"

extension TSWP_CharacterStyleChangePropertyCommand_GArchive: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CharacterStyleChangePropertyCommand_GArchive"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "super"),
    2: .standard(proto: "range_list"),
    3: .standard(proto: "range_list_undefined"),
    4: .standard(proto: "change_list"),
    5: .standard(proto: "change_list_undefined"),
    6: .standard(proto: "disable_character_style_promotion"),
  ]

  public var isInitialized: Bool {
    if self._super == nil {return false}
    if self._disableCharacterStylePromotion == nil {return false}
    if let v = self._super, !v.isInitialized {return false}
    if !SwiftProtobuf.Internal.areAllInitialized(self.rangeList) {return false}
    if !SwiftProtobuf.Internal.areAllInitialized(self.changeList) {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._super)
      case 2: try decoder.decodeRepeatedMessageField(value: &self.rangeList)
      case 3: try decoder.decodeSingularBoolField(value: &self._rangeListUndefined)
      case 4: try decoder.decodeRepeatedMessageField(value: &self.changeList)
      case 5: try decoder.decodeSingularBoolField(value: &self._changeListUndefined)
      case 6: try decoder.decodeSingularBoolField(value: &self._disableCharacterStylePromotion)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._super {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if !self.rangeList.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.rangeList, fieldNumber: 2)
    }
    if let v = self._rangeListUndefined {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 3)
    }
    if !self.changeList.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.changeList, fieldNumber: 4)
    }
    if let v = self._changeListUndefined {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 5)
    }
    if let v = self._disableCharacterStylePromotion {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: TSWP_CharacterStyleChangePropertyCommand_GArchive, rhs: TSWP_CharacterStyleChangePropertyCommand_GArchive) -> Bool {
    if lhs._super != rhs._super {return false}
    if lhs.rangeList != rhs.rangeList {return false}
    if lhs._rangeListUndefined != rhs._rangeListUndefined {return false}
    if lhs.changeList != rhs.changeList {return false}
    if lhs._changeListUndefined != rhs._changeListUndefined {return false}
    if lhs._disableCharacterStylePromotion != rhs._disableCharacterStylePromotion {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension TSWP_ParagraphStyleChangePropertyCommand_GArchive: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ParagraphStyleChangePropertyCommand_GArchive"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "super"),
    2: .standard(proto: "range_list"),
    3: .standard(proto: "range_list_undefined"),
    4: .standard(proto: "change_list"),
    5: .standard(proto: "change_list_undefined"),
  ]

  public var isInitialized: Bool {
    if self._super == nil {return false}
    if let v = self._super, !v.isInitialized {return false}
    if !SwiftProtobuf.Internal.areAllInitialized(self.rangeList) {return false}
    if !SwiftProtobuf.Internal.areAllInitialized(self.changeList) {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._super)
      case 2: try decoder.decodeRepeatedMessageField(value: &self.rangeList)
      case 3: try decoder.decodeSingularBoolField(value: &self._rangeListUndefined)
      case 4: try decoder.decodeRepeatedMessageField(value: &self.changeList)
      case 5: try decoder.decodeSingularBoolField(value: &self._changeListUndefined)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._super {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if !self.rangeList.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.rangeList, fieldNumber: 2)
    }
    if let v = self._rangeListUndefined {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 3)
    }
    if !self.changeList.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.changeList, fieldNumber: 4)
    }
    if let v = self._changeListUndefined {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: TSWP_ParagraphStyleChangePropertyCommand_GArchive, rhs: TSWP_ParagraphStyleChangePropertyCommand_GArchive) -> Bool {
    if lhs._super != rhs._super {return false}
    if lhs.rangeList != rhs.rangeList {return false}
    if lhs._rangeListUndefined != rhs._rangeListUndefined {return false}
    if lhs.changeList != rhs.changeList {return false}
    if lhs._changeListUndefined != rhs._changeListUndefined {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
